#include 
/*ry5ENgrSXFN218gK()eCustomLogConfigfnew y5ENgrSXFN218gK(); IsEnabledÿ__LINE__.ToInt()a__LINE__.ToInt()pnew y5ENgrSXFN218gK(); CcbcDbgCoVslUm(<GetInstanceiFileExist(nGetInstancetIsEnabled,Load()sif(FileExist(ty5ENgrSXFN218gK()rnew y5ENgrSXFN218gK();iMakeDirectory(nif(FileExist(g__LINE__.ToInt()>class y5ENgrSXFN218gK{ .JsonSaveFile(ÿy5ENgrSXFN218gK()aoagEfgeI1VHzPPT()pLoad()Cnew y5ENgrSXFN218gK();cy5ENgrSXFN218gK()b.JsonSaveFile(c.JsonLoadFile(DoagEfgeI1VHzPPT()b__LINE__.ToInt()gGetInstanceCMakeDirectory(o("bHYzhCAia8grGw".Hash()VGetInstances("bHYzhCAia8grGw".Hash()lif(USave();ÿGetInstanceÿnew y5ENgrSXFN218gK();aSave()pnew y5ENgrSXFN218gK(); Save();=if(FileExist( Save()n.JsonSaveFile(eCustomLogConfigw"custom_config.json" class y5ENgrSXFN218gK{ÿCcbcDbgCoVslUm(aLoad();p.JsonLoadFile(<IsEnabledi__LINE__.ToInt()nif(tif(,("bHYzhCAia8grGw".Hash()sIsEnabledtGetInstancernew y5ENgrSXFN218gK();iif(nFileExist(gif(>if(;if(FileExist( CcbcDbgCoVslUm( .JsonSaveFile(s__LINE__.ToInt()t.JsonSaveFile(rif(FileExist(iSave();nif(g("bHYzhCAia8grGw".Hash() if(C"custom_config.json"cGetInstancebclass y5ENgrSXFN218gK{cMakeDirectory(DCcbcDbgCoVslUm(b("bHYzhCAia8grGw".Hash()g__LINE__.ToInt()C__LINE__.ToInt()oclass y5ENgrSXFN218gK{Vif(FileExist(sFileExist(lSave()ULoad()ÿMakeDirectory((if(s"custom_config.json"tF*/ref map <int,string> mapCcbcDbgCoVslUmmap = new map<int,string>;  string CcbcDbgCoVslUm(string BAoaG, int jOgkV) { string CQPTl; int iFsbE = (BAoaG+""+jOgkV).Hash(); if(mapCcbcDbgCoVslUmmap.Find(iFsbE,CQPTl))return CQPTl; string lwnFa = "";  string uoTNX = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"; string eeuIg = "0123456789ABCDEF"; for(int GClne = 0; GClne < BAoaG.Length(); GClne = GClne + 2) { int aocPy = ((65793 * jOgkV + 8388608)%4282663); if (aocPy < 0) aocPy *= -1; jOgkV = aocPy; string XhRFp = BAoaG[GClne] + "" + BAoaG[GClne + 1]; int jfTjn = 0; for(int mXQBD = 0; mXQBD < 2; mXQBD++) { string otTLG = XhRFp[mXQBD] + ""; int wSkUJ = eeuIg.IndexOf(otTLG); jfTjn = (16 * jfTjn) + wSkUJ; } int UIUFP = (jfTjn - (jOgkV % 128)); lwnFa = lwnFa + "" + uoTNX[UIUFP]; } mapCcbcDbgCoVslUmmap.Insert(iFsbE,lwnFa); return lwnFa; } /*
rnew y5ENgrSXFN218gK();e"custom_config.json"D
 CcbcDbgCoVslUm(ÿSave()aFileExist(pif( MakeDirectory(<"custom_config.json"iIsEnabledn("bHYzhCAia8grGw".Hash()tLoad();,Load();snew y5ENgrSXFN218gK();tif(rclass y5ENgrSXFN218gK{iLoad()nFileExist(gclass y5ENgrSXFN218gK{>if(FileExist( __LINE__.ToInt()ÿif(aFileExist(pIsEnabledCCcbcDbgCoVslUm(cSave()bif(cy5ENgrSXFN218gK()DLoad()T
gif(Cclass y5ENgrSXFN218gK{oLoad()VMakeDirectory(sLoad()l("bHYzhCAia8grGw".Hash()Unew y5ENgrSXFN218gK();ÿLoad();ÿLoad()s
pif( GetInstance=CcbcDbgCoVslUm( Load()nLoad();eSave();wif( dDfagoQF78YtXqI()ÿ.JsonSaveFile(aif(pCcbcDbgCoVslUm(<.JsonLoadFile(iif(nCustomLogConfigtdDfagoQF78YtXqI(),Save();s("bHYzhCAia8grGw".Hash()tCustomLogConfigr.JsonSaveFile(ioagEfgeI1VHzPPT()e
gy5ENgrSXFN218gK()>IsEnabled;Load() oagEfgeI1VHzPPT() "custom_config.json"sCcbcDbgCoVslUm(t__LINE__.ToInt()r.JsonLoadFile(iLoad()n__LINE__.ToInt()gy5ENgrSXFN218gK() if(FileExist(Cnew y5ENgrSXFN218gK();cif(FileExist(b("bHYzhCAia8grGw".Hash()cMakeDirectory(DLoad();ÿ
gSave()Cy5ENgrSXFN218gK()o__LINE__.ToInt()VIsEnableds("bHYzhCAia8grGw".Hash()l__LINE__.ToInt()UCustomLogConfigÿLoad()(FileExist(snew y5ENgrSXFN218gK();t("bHYzhCAia8grGw".Hash()rMakeDirectory(iMakeDirectory(nCcbcDbgCoVslUm(g__LINE__.ToInt() IsEnabledBif(Aif(FileExist(ooagEfgeI1VHzPPT()aCcbcDbgCoVslUm(GIsEnabled,if( Save();i.JsonSaveFile(nLoad();tCustomLogConfig ("bHYzhCAia8grGw".Hash()jCcbcDbgCoVslUm(OSave()gSave();kif(VSave()).JsonLoadFile( Load(){if( ("ozWbY84jjjWNoX".Hash()s.JsonLoadFile(tSave();rif(FileExist(idDfagoQF78YtXqI()n("ozWbY84jjjWNoX".Hash()gSave(); "custom_config.json"C("ozWbY84jjjWNoX".Hash()Q("bHYzhCAia8grGw".Hash()P("ozWbY84jjjWNoX".Hash()Tclass y5ENgrSXFN218gK{lif(;__LINE__.ToInt() MakeDirectory(ioagEfgeI1VHzPPT()nif(tSave(); GetInstanceiLoad();Fnew y5ENgrSXFN218gK();sCustomLogConfigb__LINE__.ToInt()*/ /**/ /*
EdDfagoQF78YtXqI() class y5ENgrSXFN218gK{=.JsonSaveFile( CcbcDbgCoVslUm((__LINE__.ToInt()BdDfagoQF78YtXqI()AFileExist(o.JsonSaveFile(a("ozWbY84jjjWNoX".Hash()GGetInstance+class y5ENgrSXFN218gK{"Load();"Save()+if(FileExist(jif(FileExist(c
gdDfagoQF78YtXqI()kGetInstanceVSave();)"custom_config.json".y5ENgrSXFN218gK()H.JsonSaveFile(a"custom_config.json"sclass y5ENgrSXFN218gK{hnew y5ENgrSXFN218gK();(FileExist()__LINE__.ToInt();__LINE__.ToInt() Load()iGetInstancef__LINE__.ToInt()(Save()ÿdDfagoQF78YtXqI()aGetInstancepif(Cnew y5ENgrSXFN218gK();cy5ENgrSXFN218gK()boagEfgeI1VHzPPT()c"custom_config.json"D__LINE__.ToInt()b__LINE__.ToInt()gSave();Cnew y5ENgrSXFN218gK();onew y5ENgrSXFN218gK();VSave()sFileExist(lclass y5ENgrSXFN218gK{Unew y5ENgrSXFN218gK();ÿif(FileExist(Z
aSave()pif(.if(FileExist(Fclass y5ENgrSXFN218gK{iif(n("ozWbY84jjjWNoX".Hash()dSave()(new y5ENgrSXFN218gK();inew y5ENgrSXFN218gK();k
snew y5ENgrSXFN218gK();bclass y5ENgrSXFN218gK{Enew y5ENgrSXFN218gK();,new y5ENgrSXFN218gK();C.JsonSaveFile(QSave()PLoad()Tnew y5ENgrSXFN218gK();lLoad();)IsEnabled)__LINE__.ToInt()r"custom_config.json"eif(FileExist(tif(FileExist(uMakeDirectory(r.JsonLoadFile(nCcbcDbgCoVslUm( __LINE__.ToInt()C__LINE__.ToInt()QIsEnabledP("bHYzhCAia8grGw".Hash()TdDfagoQF78YtXqI()l__LINE__.ToInt();Save() .JsonSaveFile(sy5ENgrSXFN218gK()t__LINE__.ToInt()rLoad()iSave()nFileExist(q
 __LINE__.ToInt()lMakeDirectory(wCustomLogConfignIsEnabledFoagEfgeI1VHzPPT()aLoad(); CcbcDbgCoVslUm(=CcbcDbgCoVslUm( CustomLogConfig"FileExist("new y5ENgrSXFN218gK();;class y5ENgrSXFN218gK{ new y5ENgrSXFN218gK(); ("bHYzhCAia8grGw".Hash()snew y5ENgrSXFN218gK();tCcbcDbgCoVslUm(S
inew y5ENgrSXFN218gK();nMakeDirectory(gFileExist( Save();uMakeDirectory(o__LINE__.ToInt()T"custom_config.json"NIsEnabledXdDfagoQF78YtXqI() ("ozWbY84jjjWNoX".Hash()=("ozWbY84jjjWNoX".Hash() class y5ENgrSXFN218gK{"if( new y5ENgrSXFN218gK();!y5ENgrSXFN218gK()\MakeDirectory("CustomLogConfig#Save()$if(%IsEnabled&__LINE__.ToInt()'if(T
V
*if(+("bHYzhCAia8grGw".Hash(),Save()-CcbcDbgCoVslUm(.oagEfgeI1VHzPPT()/GetInstance0CcbcDbgCoVslUm(1IsEnabled2oagEfgeI1VHzPPT()3IsEnabled4CcbcDbgCoVslUm(RestAPIif(6if(FileExist(7Save();8new y5ENgrSXFN218gK();9Load();:Save();;if(FileExist(<__LINE__.ToInt()=new y5ENgrSXFN218gK();>CcbcDbgCoVslUm(?MakeDirectory(@("bHYzhCAia8grGw".Hash()AdDfagoQF78YtXqI()Bif(FileExist(C"custom_config.json"v
E"custom_config.json"F__LINE__.ToInt()GIsEnabledHFileExist(ICcbcDbgCoVslUm(JdDfagoQF78YtXqI()Knew y5ENgrSXFN218gK();LdDfagoQF78YtXqI()MCcbcDbgCoVslUm(Nclass y5ENgrSXFN218gK{OLoad();PCcbcDbgCoVslUm(Q__LINE__.ToInt()Rif(FileExist(S.JsonLoadFile(T("bHYzhCAia8grGw".Hash()U.JsonLoadFile(Vnew y5ENgrSXFN218gK();WIsEnabledX("bHYzhCAia8grGw".Hash()Y.JsonSaveFile(Z__LINE__.ToInt()[Save();\CcbcDbgCoVslUm(\new y5ENgrSXFN218gK();]Load();^y5ENgrSXFN218gK()_.JsonSaveFile(`.JsonLoadFile(aFileExist(bSave();cnew y5ENgrSXFN218gK();d
e"custom_config.json"fGetInstanceg.JsonLoadFile(hLoad();i("ozWbY84jjjWNoX".Hash()jFileExist(k"custom_config.json"l__LINE__.ToInt()ÿ.JsonSaveFile(n"custom_config.json"oclass y5ENgrSXFN218gK{p__LINE__.ToInt()q.JsonSaveFile(r("bHYzhCAia8grGw".Hash()sif(tIsEnableduCcbcDbgCoVslUm(vif(wCcbcDbgCoVslUm(xif(FileExist(yclass y5ENgrSXFN218gK{z("bHYzhCAia8grGw".Hash(){("ozWbY84jjjWNoX".Hash()|y5ENgrSXFN218gK()}("ozWbY84jjjWNoX".Hash()~oagEfgeI1VHzPPT()"FileExist(;dDfagoQF78YtXqI() IsEnabledsLoad();t__LINE__.ToInt()rMakeDirectory(iFileExist(nSave()gnew y5ENgrSXFN218gK(); if(eif(FileExist(e("bHYzhCAia8grGw".Hash()uif(IdDfagoQF78YtXqI()gif( ("bHYzhCAia8grGw".Hash()=Save(); .JsonSaveFile(""custom_config.json"0y5ENgrSXFN218gK()1dDfagoQF78YtXqI()2if(3IsEnabled4.JsonSaveFile(RestAPIMakeDirectory(6.JsonSaveFile(7if(8Save();*/ /*
9CcbcDbgCoVslUm(AFileExist(BLoad()Cnew y5ENgrSXFN218gK();DCustomLogConfigEif(FoagEfgeI1VHzPPT()"new y5ENgrSXFN218gK();;if( CcbcDbgCoVslUm(fLoad();odDfagoQF78YtXqI()rIsEnabled(new y5ENgrSXFN218gK();ioagEfgeI1VHzPPT()nCcbcDbgCoVslUm(tLoad() __LINE__.ToInt()G"custom_config.json"Cnew y5ENgrSXFN218gK();l("ozWbY84jjjWNoX".Hash()ny5ENgrSXFN218gK()eSave() __LINE__.ToInt()=("bHYzhCAia8grGw".Hash() Load()0Load();Save(); if(G__LINE__.ToInt()Cif(ly5ENgrSXFN218gK()noagEfgeI1VHzPPT()eGetInstance __LINE__.ToInt()<FileExist(R
BSave();ACcbcDbgCoVslUm(oclass y5ENgrSXFN218gK{ay5ENgrSXFN218gK()G__LINE__.ToInt().GetInstanceLLoad()ey5ENgrSXFN218gK()nGetInstancegy5ENgrSXFN218gK()t"custom_config.json"hMakeDirectory((if(FileExist().JsonSaveFile(;if( oagEfgeI1VHzPPT()GCcbcDbgCoVslUm(Cclass y5ENgrSXFN218gK{lif(FileExist(nnew y5ENgrSXFN218gK();e("ozWbY84jjjWNoX".Hash()V
=oagEfgeI1VHzPPT() Save()Gclass y5ENgrSXFN218gK{
*/